// /src/components/gamification/TodayQuestCard.tsx
// Today's Quest: Gemini-generated optional short reflection challenge (+15 XP)

import React, { useState, useEffect } from "react";
import { Target, Sparkles, CheckCircle2, ArrowRight, RefreshCw, Loader2 } from "lucide-react";
import { useGamification } from "../../context/GamificationContext";
import { fetchDailyQuest } from "../../../client/services/apiService";
import { TodayQuest } from "../../types";

interface TodayQuestCardProps {
  onStartQuestPrompt?: (prompt: string) => void;
}

export const TodayQuestCard: React.FC<TodayQuestCardProps> = ({ onStartQuestPrompt }) => {
  const { stats, recordQuestCompleted } = useGamification();
  const [quest, setQuest] = useState<TodayQuest | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isCompleted, setIsCompleted] = useState(false);

  const todayStr = new Date().toISOString().split("T")[0];
  const questActivityKey = `quest_${todayStr}`;

  useEffect(() => {
    // Check if quest was already completed today
    if (stats.completedActivities && stats.completedActivities[questActivityKey]) {
      setIsCompleted(true);
    }

    let isMounted = true;
    async function loadQuest() {
      if (stats.todayQuest && stats.todayQuest.dateString === todayStr) {
        setQuest(stats.todayQuest);
        return;
      }

      setIsLoading(true);
      try {
        const res = await fetchDailyQuest({});
        if (isMounted && res && res.prompt) {
          setQuest({
            id: `quest_${todayStr}`,
            title: res.title || "Daily Reflection Quest",
            prompt: res.prompt,
            xpReward: 15,
            dateString: todayStr,
            completed: false,
          });
        }
      } catch (err) {
        console.warn("Could not load daily quest from Gemini:", err);
        if (isMounted) {
          setQuest({
            id: `quest_${todayStr}`,
            title: "Observe Without Fixing",
            prompt: "Describe one problem you're facing today without trying to solve it.",
            xpReward: 15,
            dateString: todayStr,
            completed: false,
          });
        }
      } finally {
        if (isMounted) setIsLoading(false);
      }
    }

    loadQuest();
    return () => {
      isMounted = false;
    };
  }, [stats.completedActivities, stats.todayQuest, todayStr, questActivityKey]);

  const handleRefreshQuest = async () => {
    setIsLoading(true);
    try {
      const res = await fetchDailyQuest({});
      if (res && res.prompt) {
        setQuest({
          id: `quest_${todayStr}_${Date.now()}`,
          title: res.title || "Daily Reflection Quest",
          prompt: res.prompt,
          xpReward: 15,
          dateString: todayStr,
          completed: false,
        });
      }
    } catch (err) {
      console.warn("Refresh quest error:", err);
    } finally {
      setIsLoading(false);
    }
  };

  const handleStartQuest = async () => {
    if (!quest) return;
    if (onStartQuestPrompt) {
      onStartQuestPrompt(quest.prompt);
    }
  };

  const handleMarkComplete = async () => {
    setIsCompleted(true);
    await recordQuestCompleted();
  };

  return (
    <div className="bg-[#FFFCF7] border border-[#E8D6C3] rounded-3xl p-6 sm:p-7 shadow-xs space-y-4 relative overflow-hidden">
      {/* Background Soft Glow */}
      <div className="absolute top-0 right-0 w-40 h-40 bg-[#E8B84A]/10 rounded-full blur-2xl pointer-events-none" />

      {/* Header */}
      <div className="flex items-center justify-between border-b border-[#E8D6C3] pb-3.5 relative z-10">
        <div className="flex items-center gap-2.5">
          <div className="w-9 h-9 rounded-xl bg-[#E8B84A]/20 border border-[#E8B84A]/50 flex items-center justify-center text-lg text-[#6B4938] shrink-0">
            🎯
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h3 className="text-base font-serif font-bold text-[#3B2922]">
                Today's Quest
              </h3>
              <span className="text-[10px] font-mono font-bold bg-[#E8B84A]/20 text-[#6B4938] px-2 py-0.5 rounded-full border border-[#E8B84A]/30">
                +15 XP
              </span>
            </div>
            <p className="text-[11px] text-[#6B4938] font-serif italic">
              An optional short challenge generated by Gemini to widen your perspective.
            </p>
          </div>
        </div>

        <button
          onClick={handleRefreshQuest}
          disabled={isLoading}
          className="p-2 rounded-xl bg-[#FFF8EE] hover:bg-[#F5EBE1] border border-[#E8D6C3] text-[#6B4938] hover:text-[#3B2922] transition-colors cursor-pointer disabled:opacity-40"
          title="Generate alternative reflection quest"
        >
          <RefreshCw size={14} className={isLoading ? "animate-spin text-[#E8B84A]" : ""} />
        </button>
      </div>

      {/* Quest Body */}
      {isLoading ? (
        <div className="py-6 text-center space-y-2">
          <Loader2 size={20} className="animate-spin text-[#E8B84A] mx-auto" />
          <p className="text-xs text-[#6B4938] font-serif italic">
            Gemini is formulating today's quiet inquiry...
          </p>
        </div>
      ) : quest ? (
        <div className="space-y-4 relative z-10">
          <div className="p-4 rounded-2xl bg-[#FFF8EE] border border-[#E8D6C3] space-y-1.5">
            <span className="text-[10px] uppercase font-mono tracking-wider text-[#E8B84A] font-bold block">
              {quest.title}
            </span>
            <blockquote className="text-sm sm:text-base font-serif italic text-[#3B2922] leading-relaxed">
              "{quest.prompt}"
            </blockquote>
          </div>

          {/* Action Buttons */}
          <div className="flex flex-wrap items-center justify-between gap-3 pt-1">
            {isCompleted ? (
              <span className="text-xs font-serif font-bold text-[#A8B29A] bg-[#FFFCF7] border border-[#A8B29A]/40 px-3.5 py-2 rounded-xl flex items-center gap-1.5 shadow-2xs">
                <Sparkles size={14} className="text-[#E8B84A]" />
                ✨ Quest Complete (+15 XP)
              </span>
            ) : (
              <div className="flex items-center gap-2.5 w-full sm:w-auto justify-end ml-auto">
                <button
                  onClick={handleMarkComplete}
                  className="px-3.5 py-2 rounded-xl bg-[#FFF8EE] hover:bg-[#F5EBE1] border border-[#E8D6C3] text-xs font-serif font-semibold text-[#6B4938] hover:text-[#3B2922] transition-colors cursor-pointer"
                >
                  Mark Complete
                </button>

                <button
                  id="start-quest-btn"
                  onClick={handleStartQuest}
                  className="px-4 py-2 rounded-xl bg-[#6B4938] hover:bg-[#3B2922] text-[#FFFCF7] text-xs font-serif font-bold flex items-center gap-2 shadow-xs transition-all cursor-pointer border border-[#E8B84A]/30 group"
                >
                  <span>Start Quest</span>
                  <ArrowRight size={14} className="text-[#E8B84A] group-hover:translate-x-0.5 transition-transform" />
                </button>
              </div>
            )}
          </div>
        </div>
      ) : null}
    </div>
  );
};
